### ISSUE TITLE
Feature: Mutation score badge

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker#349]
Add a mutation score badge!
![badge](https://img.shields.io/badge/mutation-85.6-green.svg)

## Todo:
- [ ] Create a cloud based solution where people can sign on with their github account, add their projects and generate an api key
- [ ] Create a reporter that can report the mutation score to the cloud based solution using an api key (which can be encrypted using travis/appveyor)
- [ ] Create a url like this: https://[our-cloud-based-service]/badge/[github-user]/[github-repo-name]/[branch-name]. When we get an HTTP GET on that URL, we should lookup the current mutation score in the database and proxy the http request to https://img.shields.io/badge/mutation-[mutation-score]-[color].svg

## Style guide
Which one do we like best?

### Stryker

![badge](https://img.shields.io/badge/stryker-85.6-green.svg)
![badge](https://img.shields.io/badge/stryker-79-yellow.svg)
![badge](https://img.shields.io/badge/stryker-59-red.svg)

### Mutation score

![badge](https://img.shields.io/badge/mutation_score-85.6-green.svg)
![badge](https://img.shields.io/badge/mutation_score-79-yellow.svg)
![badge](https://img.shields.io/badge/mutation_score-59-red.svg)

### Mutation

![badge](https://img.shields.io/badge/mutation-85.6-green.svg)
![badge](https://img.shields.io/badge/mutation-79-yellow.svg)
![badge](https://img.shields.io/badge/mutation-59-red.svg)

**Comment by mthmulders** [comment]
Oh, this is a cool idea! I'd love to contribute to such a back end component. I'd stick with the first option (just "stryker"), it's short and concise.

**Comment by nicojs** [comment]
I actually like "mutation score" best. It explains what it is and people that are interested in it can click on it to learn more about mutation testing and what a mutation score is.

@mthmulders work on the backend is tracked here: https://github.com/stryker-mutator/stryker-badge

**Comment by sharikovvladislav** [comment]
Anything specific on tools what you want to use in frontend part of the component?

**Comment by mthmulders** [comment]
I just started to give [create-react-app with TypeScript](https://github.com/wmonk/create-react-app-TypeScript) a try.

**Comment by sharikovvladislav** [comment]
Do you have anybody experienced in React? Can I submit PR's? Do you have any structure for front end application? Am I right that front end and back end will communicate through API?

**Comment by mthmulders** [comment]
My idea would be to write the front end app in TypeScript, just like the back end. I was thinking of using React and [Material UI](http://material-ui.com/) to create user interfaces. As for now, I don't see any [_need_ of using Redux](https://medium.com/@dan_abramov/you-might-not-need-redux-be46360cf367) yet. Don't get me wrong, I think Redux is fantastic, but as the linked article explains, all the awesomeness comes with a price. And since I think we don't _need_ the awesomeness, I don't really feel like paying that price :).

There are already some parts of the back end app:
* an API endpoint that authorizes the user using GitHub OAuth;
* an API endpoint that lists all GitHub repos the user has access to;
* and I [envision](https://github.com/stryker-mutator/stryker-badge/blob/master/docs/backend.md) a few more endpoints to expose all desired functionality.

There already is a CI build for the back end, and I was planning to integrate the aforementioned [create-react-app-typescript](https://github.com/wmonk/create-react-app-TypeScript) into that and see if I can get _one_ CI build that _first_ builds the front end app and then copies that to the `public` folder of the back end app. At the end of that build, we would have a back end with the front end "build in", which would make it easier to deploy the whole package.

But that's just my two cents on this idea. Some of them were discussed with @nicojs, some were not. I'm curious about your ideas and what you would like to contribute!

**Comment by sharikovvladislav** [comment]
What exact price do you think we will pay for using Redux? Why do you think using TypeScript is a good idea? What benefits will you get from using TypeScript?

Did you think about [Semantic UI](https://react.semantic-ui.com/introduction)? I have only awesome reviews about it from my colleagues. 

I don't have a lot react experience and I want to try it. If it's ok - I can do some PR's.

I tried redux in as ngrx with Angular 4 and it is awesome. Ye you have some tradeoffs but I think you gain same as you gain from TypeScript: you can develop your project more easily. You understand how data flows. You have good tooling. You have structure (redux dictates structure and adds some boilerplate (one of tradeoffs).

**Comment by mthmulders** [comment]
My main "concerns" (although that's a big word) with Redux are quite well explained by its author in the article that I linked to earlier. It's absolutely good stuff, but my two toy projects with React and Redux convinced me that for small, simple stuff it's a bit overkill. So I'd rather start _without_ Redux and only add it once we feel like we actually _need_ it to solve certain problems. I prefer to start as simple as possible.

In my experience with React and TypeScript, the latter really helps the former. It allows your editor to suggest you when you forgot something, assist you in selecting values from your current scope, etc. In fact, it gives you all the goodness from strongly typed languages *plus* all the goodness from React. What else could you want? :) 

Yes, I'd suggest to use Jest for testing, simply because it's so easy there's no reason _not_ to do it. And it will help to ensure the app(s) works correctly.

As for me personally, Semantic UI is on my list of "stuff to try", didn't try it yet but it looks pretty nice. @nicojs, how would you feel about leaving Material Design *and* Bootstrap and trying Semantic UI?

**Comment by sharikovvladislav** [comment]
> What else could you want? :)

I just want you to say again why TypeScript is good. TypeScript is good since you have great experience in you IDE.

Redux is good since you have great experience with managing the store. Why don't you think that TypeScript is overkill for such small app? 

I think that you can easily replace `Redux` with `TypeScript` in that phrase: 

> Redux convinced me that for small, simple stuff it's a bit overkill.

It absolutely fits :)

Also: 

> I prefer to start as simple as possible.

`Non-TypeScript` is simpler than `TypeScript` :)

But as you wish :)

Will you have some ready-for-development tasks for outsourcing? If yes and you can spend some time to explain what do you want more verbose, I can take some.

**Comment by sharikovvladislav** [comment]
Any news?

**Comment by ptoonen** [comment]
@sharikovvladislav there most definitely is: https://github.com/stryker-mutator/stryker-badge/ work-in-progress, but slowly but surely we're getting there.

**Comment by simondel** [comment]
@webdevian Perhaps this is something you'll like as well! (once it's in beta) You seem fond of badges 😉

**Comment by webdevian** [comment]
Yes I'm definitely keeping an eye on this!

**Comment by nicojs** [comment]
This feature is implemented some time ago. See https://dashboard.stryker-mutator.io/
