### ISSUE TITLE
Prepare 1.0.0 release

### ISSUE THREAD

**Issue by simondel** [stryker-mutator/stryker#654]
With the 1.0.0 release with Stryker we will make the following changes:

### Preparation

- [x] #365
- [x] #667 
- [x] #799 (release v1 of dependencies)
- [x] #920 (support big projects)
- [x] [Rename 'project' config key to 'projectType'](https://github.com/stryker-mutator/stryker/issues/1076)
- [x] [Rename 'timeoutMs' config key to 'timeoutMS'](https://github.com/stryker-mutator/stryker/issues/860)

### Execution

- [x] Remove deprecated Factories from stryker-api.
- [x] Remove ES5 mutator
- [x] Set 'javascript' as the default mutator
- [x] Remove deprecated reporter config key
- [x] Remove deprecated project config key
- [x] Remove deprecated 'default' projectType for jest (in favor of 'custom')
- [x] Remove deprecated timeoutMs config key
- [x] Rename packages:
  * `stryker` => `@stryker-mutator/core`
  * `stryker-xxx-yyy` => `@stryker-mutator/xxx-yyy`
  * `stryker-jasmine` => `@stryker-mutator/jasmine-framework`
  * `stryker-typescript` => `@stryker-mutator/typescript`
- [x] Remove `config` key from being injectable
- [x] Remove `getLogger` and `setImplementation` from `stryker-api/logging`
- [x] Remove all deprecated apis/messages/etc
- [x] Update plugin loader to load plugins from `@stryker-mutator` (instead of `stryker-`)
- [x] Enable lerna versioning mode (not independent, other one)
- [x] Update `stryker-cli` to install `@stryker-mutator/core` instead of `stryker` and `stryker-api`
- [x] Update package.json keywords to @stryker-mutator/
- [x] Update keyword plugin to 'stryker-mutator-plugin'

### Clean up

- [x] Deprecate Stryker packages: https://docs.npmjs.com/cli/deprecate (let's wait ~ a week for this)
- [x] Write awesome blog article
- [x] Update handbook https://github.com/stryker-mutator/stryker-handbook/tree/v1-release
- [x] Update website quickstart: https://github.com/stryker-mutator/stryker-mutator.github.io/tree/v1-release

_This original post will be kept up-to-date._

**Comment by nicojs** [comment]
Why would we no longer support mutators as strings? `mutator: 'typescript'` could be a shorthand for ```js
mutator: {
   type: 'typescript',
   excludedMutations: []
}
```

**Comment by simondel** [comment]
I posted that here: https://github.com/stryker-mutator/stryker/pull/652#issuecomment-373418955

**Comment by simondel** [comment]
What about renaming the `reporter` property of the stryker config to `reporters`? It's an array after all. We could already implement this with a deprecation warning for people still using the property `reporter` and remove the `reporter` property in 1.0.0

**Comment by simondel** [comment]
I created #793 and I have updated the main post of this issue

**Comment by nicojs** [comment]
I've created #799 and updated the main post.

**Comment by kmdrGroch** [comment]
@simondel, @nicojs I am trying to solve some easy issues and refactors you need. I am quite newbie in your project, try to understand how it really works, and to understand TS in 100%. Do you have some instructions / tips, how can I work out / find out myself in that big project?

**Comment by simondel** [comment]
Awesome :) We have a mono-repo. All the stryker plugins that we maintain ourselves are in here. We use Lerna to bind it all together and ensure the packages work together locally. If you run commands such as `npm install` from the root of the repo, they will be executed in each package.

Perhaps a nice one to start with is this: https://github.com/stryker-mutator/stryker/issues/1076
It's isolated to two packages which are a lot smaller in size than the main codebase of Stryker 👍 You could either fix both packages in one pull request or split it up into two pull requests. Whatever works for you.

I would also suggest reading the [contribution guide](https://github.com/stryker-mutator/stryker/blob/master/CONTRIBUTING.md) if you haven't read it already.

Unfortunately we can't make all the changes for 1.0.0. I'll split the original post up between preparation and execution.

**Comment by kmdrGroch** [comment]
@simondel i don't know if you checked what I have done yesterday in fork. I could make pull request today but i have solved #860 and #654 i think. Also did some minor changes to mutators

**Comment by kmdrGroch** [comment]
also i have question about packages/stryker-karma-runner/package.json. In all files you define ``project [projectType]`` to be ``default`` and then you change it to ``custom``. Is it issue or I missed some line in config

**Comment by kmdrGroch** [comment]
I have tried to test but it crashes on ```js
1) A babel project with the `only` option enabled
       should be able to transpile the input files:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\Users\19gro\Desktop\stryker\packages\stryker-babel-transpiler\test\integration\BabelProjects.it.js)```

**Comment by nicojs** [comment]
Additional stuff to do:

* Rename packages: 
 - `stryker` => `@stryker-mutator/core`
 - `stryker-xxx-yyy` => `@stryker-mutator/xxx-yyy`
 - `stryker-jasmine` => `@stryker-mutator/jasmine-framework`
 - `typescript` => `@stryker-mutator/typescript`

* Remove all deprecated apis/messages/etc
* Update plugin loader to load plugins from `@stryker-mutator` (instead of `stryker-`)
* Enable lerna versioning mode (not independent, other one)
* Deprecate Stryker packages: https://docs.npmjs.com/cli/deprecate (let's wait ~ a week for this)
* Write awesome blog article

**Comment by simondel** [comment]
Since we released it, let's close this :)

**Comment by nicojs** [comment]
Are you sure it was well prepared? ;)
